### ISSUE TITLE
提取pitch时报错

### ISSUE THREAD

**Issue by plusmultiply** [anyvoiceai/MassTTS#5]
在提取pitch那一步：

提取一下所需要的pitch,随后用于计算pitch的值
echo得到的值运行一下, 如果在colab上的话可以删除echo直接运行.

`!PYTHONPATH={start_path}/codes/NeMo CUDA_VISIBLE_DEVICES=0 python {start_path}/codes/NeMo/examples/tts/fastpitch.py \
    train_dataset={start_path}/metas/nemo/train_manifest.json \
    validation_datasets={start_path}/metas/nemo/val_manifest.json \
    sup_data_path={start_path}/sup_data \
    exp_manager.exp_dir={start_path}/tmp \
    bert_path={start_path}/bert_feats \
    trainer.strategy=null name=testing pitch_mean=130.01991 pitch_std=50.18665 trainer.max_epochs=1`
会报错
`MassTTS/codes/NeMo/nemo/collections/common/tokenizers/text_to_speech/tts_tokenizers.py", line 832, in <listcomp>
    return [self._token2id[p] for p in ps]
KeyError: ','`
以及
`hydra.errors.InstantiationException: Error in call to target 'nemo.collections.tts.data.dataset.TTSDataset':
KeyError(',')
full_key: train_ds.dataset`
请问有什么解决方法吗

**Comment by imsai-sh** [comment]
> 在提取pitch那一步：
> 
> 提取一下所需要的pitch,随后用于计算pitch的值 echo得到的值运行一下, 如果在colab上的话可以删除echo直接运行.
> 
> `!PYTHONPATH={start_path}/codes/NeMo CUDA_VISIBLE_DEVICES=0 python {start_path}/codes/NeMo/examples/tts/fastpitch.py \ train_dataset={start_path}/metas/nemo/train_manifest.json \ validation_datasets={start_path}/metas/nemo/val_manifest.json \ sup_data_path={start_path}/sup_data \ exp_manager.exp_dir={start_path}/tmp \ bert_path={start_path}/bert_feats \ trainer.strategy=null name=testing pitch_mean=130.01991 pitch_std=50.18665 trainer.max_epochs=1` 会报错 `MassTTS/codes/NeMo/nemo/collections/common/tokenizers/text_to_speech/tts_tokenizers.py", line 832, in <listcomp> return [self._token2id[p] for p in ps] KeyError: ','` 以及 `hydra.errors.InstantiationException: Error in call to target 'nemo.collections.tts.data.dataset.TTSDataset': KeyError(',') full_key: train_ds.dataset` 请问有什么解决方法吗

同样的问题，请问解决了吗
